# Generated by Django 5.1.3 on 2024-12-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_user_post_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='user',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='postId',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='album',
            new_name='albumId',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='userId',
        ),
    ]
